### ISSUE TITLE
Accuracy Discrepancy

### ISSUE THREAD

**Issue by prabhd33ps** [YonghaoHe/Light-And-Fast-Object-Detectors#33]
I have tried to get the result with WIDERFACE evaluation and get the result for LFD_L — Large

Below is the score 
 ==================== Results ====================
Easy   Val AP: 0.5960946420764421
Medium Val AP: 0.6995630658106545
Hard   Val AP: 0.7579042623709009
=================================================

These values are quite different from the results given on the repo.

Am I missing something?

**Comment by Tsuuuki223** [comment]
Hi, I am also trying with this repo.
Are you using the python evaluation code https://github.com/wondervictor/WiderFace-Evaluation ?
When I use this code, I get the same precision with you.
But when I tried official evaluation code that was written in matlab code  http://shuoyang1213.me/WIDERFACE/
I got easy 0.812/midium 0.794/hard 0.637.
It looks normal than python evaluation code, but still can not reach the pricision in this repo.
I also want to ask about this situation.

**Comment by prabhd33ps** [comment]
@KidChu Yeah exactly the same code I have used.

I struggled to use http://shuoyang1213.me/WIDERFACE/ for getting the exact values. Where do they store the value with that code?

**Comment by YonghaoHe** [comment]
@prabhd33ps obviously, results you get is incorrect. Mak sure that you use [evaluation.py](https://github.com/YonghaoHe/LFD-A-Light-and-Fast-Detector/blob/master/WIDERFACE_train/evaluation.py) in the right way. You can exam some qualitative results. I use the matlab code only, so I do not know about python evaluation code.

**Comment by Tsuuuki223** [comment]
> @KidChu Yeah exactly the same code I have used.
> 
> I struggled to use http://shuoyang1213.me/WIDERFACE/ for getting the exact values. Where do they store the value with that code?

Change pred_dir in wider_eval.m, and spicify legend_name, then click 'run', you can get a plot with many models.
If you dont want to see other models, you can delete folders in ./eval_tools/plot/baselines/Val/setting_int/
Then the plot will only have one result.

But even if I tried matlab code, I still can not get result in this repo, with only 0.637(hard) with XS model.
I am wondering if the author can tell me why. Thanks a lot.

**Comment by Tsuuuki223** [comment]
Well, I found an interesing error in this code.
In WIDERFACE_train/evaluation.py, original parameters are classification_threshold = 0.01 and nms_threshold = 0.4,
if I use this parameter, I can get 0.866/0.877/0.840 just like README, but if you save result images, you will find those detection results have many FP results, and can not be used...
Maybe you set classification_threshold much higher, e.g. 0.5 in predict.py, but this time it can not get mAP > 0.8.

**Comment by prabhd33ps** [comment]
Thank you @YonghaoHe, I will have a look again.

Thank you @KidChu, I have tried the same results with matlab and python code. Accuracies are different. I will try to run it with original parameters classification_threshold = 0.01 and nms_threshold = 0.4. Just staying hopeful. :)

**Comment by Tsuuuki223** [comment]
@prabhd33ps Hi, are you still dealing with the mAP problem?
I have found a solution:
In LFD results, there is a line 0 0 0 0 0.001 at the beginning of the txt. It doesn't matter in Matlab code, but in LFD it courses problem like you mentioned in this issue.
To fix this problem, change read_pred_file in evaluation.py: lines = lines[3:](to ignore the first zero result)
Then I think everything will be fine!
Good luck!

**Comment by prabhd33ps** [comment]
Kudos to @KidChu . This is the root cause. Thank you so much.
