### ISSUE TITLE
Too many FP results with classification_threshold=0.01

### ISSUE THREAD

**Issue by Tsuuuki223** [YonghaoHe/Light-And-Fast-Object-Detectors#35]
Hi, thank you very much for your brillant work.
In WIDERFACE_train/evaluation.py ,classification_threshold was set to 0.01, if I do evaluation with this value, I can get the extact mAP 0.866 | 0.877 | 0.839 as you mentioned in README, but it seems there are to many FP results. You may check the following image for reference.
![res](https://user-images.githubusercontent.com/24228655/129138435-5669209a-4893-448a-9e05-2319fddac082.jpg)
In WIDERFACE_train/predict.py, classification_threshold was set to 0.5, then it can get right result, but when I use this value to do evaluation with LS model, it can only get mAP  0.812/0.794/0.637.
So I think maybe mAP results in LFD for WIDERFACE are reached with an improper parameter. I would be appreciate if you can save image results in evaluation.py with classification_threshold=0.01 and check those results.
Looking forward to your reply.

**Comment by YonghaoHe** [comment]
@KidChu Actually everything is OK!
You should make something clear first. When evaluating the model, we set threshold to a small value, say 0.01 here, for recalling as many candidates as possible. Of cause, this will produce a lot of FP, which is illustrated in your picture.
However, if you use the model in the product, you should set the threshold to a relative larger value, say 0.5 or higher. This is to keep high precision but may reduce recall. In the part of Qualitative Results, we set threshold to 0.5 to obtain the final results.
I hope this will help you.

**Comment by Tsuuuki223** [comment]
Hi @YonghaoHe , Thank you for your reply!
And I am sorry that I misunderstood how to calculate mAP.
I thought you did a really brilliant work. Thanks again!
