### ISSUE TITLE
Are negative samples required? 

### ISSUE THREAD

**Issue by kb1ooo** [YonghaoHe/Light-And-Fast-Object-Detectors#43]
Most detection algorithms don't require negative samples because everything outside bounding box regions is considered "negative".  However, looking at some of the example datasets for LFD, generating negative samples explicitly seems to be part of the training data generation process.    Can you provide some guidance on the proper way to put together a dataset for training the detector on a set of objects?

**Comment by YonghaoHe** [comment]
@kb1ooo Pure negative samples (without any foreground object bboxes) are surely helpful to reduce false positives, always resulting in better performance. In academia, we do not pay much attention to public datasets themselves, and follow some conventions to use the datasets. For example, one training rule is to resize the entire image so as to have the shorter side in [600, 800] in COCO. But in practice, we try to use the dataset in a more effective way, like adding pure negative samples.

**Comment by kb1ooo** [comment]
@YonghaoHe Thanks for the clarification.
